"""empty message

Revision ID: f5837a995624
Revises: 81c7a3244390
Create Date: 2026-05-20 21:43:31.811465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5837a995624'
down_revision: Union[str, Sequence[str], None] = '81c7a3244390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_hashes', sa.Column('path_file', sa.String(length=255), nullable=False))
    op.drop_column('file_hashes', 'object_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_hashes', sa.Column('object_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('file_hashes', 'path_file')
    # ### end Alembic commands ###
